CREATE TABLE IF NOT EXISTS ORDERS (
      ORDER_ID          UUID PRIMARY KEY
    , CUSTOMER_EMAIL    VARCHAR(100)
    , ORDER_DATE        TIMESTAMP
    , AMOUNT            NUMERIC(10,2)
    , CURRENCY          VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS CURRENCY (
      CURR_DATE       INTEGER NOT NULL
    , CURR_TIME       INTEGER NOT NULL
    , CURR_CODE       VARCHAR(10) NOT NULL
    , RATE            FLOAT NOT NULL
    , TIMESTAMP       TIMESTAMP NOT NULL
    , LOAD_ID         BIGINT NOT NULL
);