CREATE TABLE IF NOT EXISTS ORDERS_EUR
(
    ORDER_ID          UUID NOT NULL PRIMARY KEY,
    CUSTOMER_EMAIL    VARCHAR(255),
    ORDER_DATE        TIMESTAMP,
    AMOUNT_EUR        NUMERIC(10, 2),
    ORIGINAL_AMOUNT   NUMERIC(10, 2),
    ORIGINAL_CURRENCY CHAR(3)
);

CREATE TABLE IF NOT EXISTS DIM_CURR_PAIR (
    BASE        VARCHAR(10),
    QUOTE       VARCHAR(10),
    RATE        FLOAT,
    IS_CURRENT  INTEGER
);

CREATE TABLE IF NOT EXISTS REF_CURRENCY (
      CURR_CODE VARCHAR(10)  PRIMARY KEY
    , CURR_DESC VARCHAR(100) NOT NULL
);


CREATE EXTENSION IF NOT EXISTS postgres_fdw;

CREATE SERVER STG_SERVER
FOREIGN DATA WRAPPER POSTGRES_FDW
OPTIONS (
    host '172.18.0.4',
    dbname 'postgres',
    port '5432'
);

CREATE USER MAPPING FOR CURRENT_USER
SERVER STG_SERVER
OPTIONS (
    user 'postgres',
    password 'postgres'
);

CREATE SCHEMA STG;

IMPORT FOREIGN SCHEMA PUBLIC
FROM SERVER STG_SERVER
INTO STG;

CREATE OR REPLACE VIEW STG_CURRENCY AS
SELECT *
FROM STG.CURRENCY;

CREATE OR REPLACE VIEW STG_ORDERS AS
SELECT *
FROM STG.ORDERS;